### ISSUE TITLE
Error calling fit function, classes of type String (Y)

### ISSUE THREAD

**Issue by y0uCeF** [danielhomola/mifs#11]
Hello,
I'm trying to do feature selection for some Microarray data using this module but I'm failing to do so. My target Y contains values of type string (S3) which represent class names. The execution of
```python
feat_selector = mifs.MutualInformationFeatureSelector()
feat_selector.fit(X, Y)
```
fails with the following error :
```python 
warnings.warn("Variables are collinear.")
Traceback (most recent call last):
  File "main.py", line 69, in <module>
    feat_selector.fit(X, Y.tolist())
  File "/usr/lib/python2.7/site-packages/mifs-0.0.1.dev0-py2.7.egg/mifs/mifs.py", line 149, in fit
    return self._fit(X, y)
  File "/usr/lib/python2.7/site-packages/mifs-0.0.1.dev0-py2.7.egg/mifs/mifs.py", line 193, in _fit
    self.X, y = self._check_params(X, y)
  File "/usr/lib/python2.7/site-packages/mifs-0.0.1.dev0-py2.7.egg/mifs/mifs.py", line 308, in _check_params
    if self.categorical and np.any(self.k > np.bincount(y)):
TypeError: Cannot cast array data from dtype('S3') to dtype('int64') according to the rule 'safe'
```
I don't know a lot about these methods, does my Y have to be an Integer?

**Comment by danielhomola** [comment]
you'll have to convert your outcome variable to integers. you can do it easily with:
http://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.LabelEncoder.html

**Comment by y0uCeF** [comment]
Thanks for your quick response, I'll give it a try. 
It was more of a question than an issue, I just didn't know where to ask.
