### ISSUE TITLE
Bug: Issue in calculation of MI of unselected features with the previously selected feature in S

### ISSUE THREAD

**Issue by swapnilkura-tal** [danielhomola/mifs#19]

**Comment by danielhomola** [comment]
Can you please try the latest version of the code and report back if you still encounter the bug? Thanks!

**Comment by swapnilkura-tal** [comment]
I had tested the code changes and it worked fine for me.

Thanks,
Swapnil

**Comment by gracewang723** [comment]
> Can you please try the latest version of the code and report back if you still encounter the bug? Thanks!

I tried, but the error was same.

**Comment by gracewang723** [comment]
> Can you please try the latest version of the code and report back if you still encounter the bug? Thanks!

I applied the last version, the error is All-NaN slice encountered

    S, F = self._add_remove(S, F, bn.nanargmax(xy_MI))
    ValueError: All-NaN slice encountered
