### ISSUE TITLE
blog post link is not working

### ISSUE THREAD

**Issue by cjen07** [danielhomola/mifs#34]
hi 

I am intereted in your work, and it seems that the blog post link in readme is not valid

I hope to learn more from your blog

thanks

**Comment by danielhomola** [comment]
http://danielhomola.com/2016/01/31/mifs-parallelized-mutual-information-based-feature-selection-module/

**Comment by impulsecorp** [comment]
It is now at https://danielhomola.com/feature%20selection/phd/mifs-parallelized-mutual-information-based-feature-selection-module/

**Comment by danielhomola** [comment]
thanks, fixed it now
