### ISSUE TITLE
Error when importing SelectorMixin

### ISSUE THREAD

**Issue by danielbunnik** [danielhomola/mifs#40]
Hi, 

First of all thanks for this amazing package! It literally saved my life!!

When I tried to import the package it failed with the following error:
ModuleNotFoundError: No module named 'sklearn.feature_selection.base'

I changed the following line of code in the mifs.py file for myself and that solved the issue for me. I am a bit new to github and programming so maybe I did something else wrong that created the problem for me. Nevertheless I thought it could not hurt to let you know ;)

from sklearn.feature_selection.base import SelectorMixin
To: 
from sklearn.feature_selection import SelectorMixin

**Comment by danielhomola** [comment]
Hi Dan,

Thanks, this is to do with the fact that in newer versions of  scikit-learn the `SelectorMixin` was moved. In the requirements.txt we are expecting `scikit-learn>=0.17.1`, i.e. as long as the version is higher than 0.17.1 then we're good, but around 0.2.0+ this breaking change in the API was introduced.. 

Glad you could fix it, thanks for noting it!
